config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("listing.urls")),
    path('account/', include("users.urls", namespace="users")),
    path('', include("contact.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import (Login, Logout, Register, CustomUserUpdate,
                         ProfileUpdateView,ChangePasswordView
                         )

app_name = "users"

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
    path('update_user/', CustomUserUpdate.as_view(), name='update_user'),
    path('update_profile/', ProfileUpdateView.as_view(), name='update_profile'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),

]

listing/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class Country(models.Model):
    name = models.CharField(max_length=50)
    created_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Region(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=255)
    region = models.ForeignKey(Region, models.CASCADE, related_name="region_city")
    created_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
class Address(models.Model):
    name = models.CharField(max_length=100)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    


class Listing(models.Model):

    class Type(models.TextChoices):
        HOUSE = "HS", "House"
        APARTMENT = "AP", "Apartment"

    class Status(models.TextChoices):
        SALE = "SL", "Sale"
        RENT = "RN", "Rent"
        DONE = "DN", "Done"
        
    class PriceType(models.TextChoices):
        s = "$", "$"
        sum ="Sum", "Sum"

    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    about = models.TextField()
    l_type = models.CharField(max_length=2, choices=Type.choices, default=Type.APARTMENT)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.RENT)
    number_of_rooms = models.PositiveIntegerField()
    price = models.FloatField()
    price_type = models.CharField(max_length=10, choices=PriceType.choices, default=PriceType.sum)
    owner = models.ForeignKey(get_user_model(), models.CASCADE, related_name="user_listing")
    area = models.CharField(max_length=255)
    city = models.ForeignKey(City, models.CASCADE, related_name="city_listing")
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name="country_listing")
    created_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.address

    def get_absolute_url(self):
        return reverse("listing_app:property_detail", args=[str(self.pk)])


class Image(models.Model):
    image = models.ImageField(upload_to="photos/")
    listing = models.ForeignKey(Listing, models.CASCADE, related_name="listing_images")

    def __str__(self):
        return self.image.name[:-5]

users/forms.py
from django import forms
from django.forms import ModelForm
from .models import CustomUser, Profile


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class CustomerUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'phone_number', 'telegram_username', 'is_agent',
                  'password', 'confirm_password']


class CustomerUserUpdateForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'phone_number', 'telegram_username', 'is_agent']


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput)
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")
        if new_password1 != new_password2:
            raise forms.ValidationError("Yangi kiritilgan parollar mos kelmadi!")


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'is_agent',
                  'telegram_username', 'x_link', 'm_link', 'l_link', 'profile_image']
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['user'].queryset = CustomUser.objects.filter(pk=user.pk)


class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'is_agent',
                  'telegram_username', 'x_link', 'm_link', 'l_link', 'profile_image']

templates/change-password.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Update Password {% endblock %}

{% block content %}
<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Hello : <span class="orange strong">{{ username }}</span></h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->

<!-- property area -->
<div class="content-area user-profiel" style="background-color: #FCFCFC;">&nbsp;
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 profiel-container">

                <form action="{% url 'users:change_password' %}" method="post">
                    {% csrf_token %}
                    <div class="profile-header text-center">
                        <h3>
                            <b>UPDATE</b> YOUR PASSWORD <br>
                            <small>All changes will be sent to your e-mail.</small>
                        </h3>
                        <hr>
                    </div>

                <div class="clear">
                    <div class="col-sm-10 col-sm-offset-1">
                        <div class="form-group">
                            <label for="id_old_password">Old Password:</label>
                            <input id="id_old_password" name="old_password" type="password" class="form-control">
                            {% if form.errors.old_password %}
                                <p class="error">{{ form.errors.old_password }}</p>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="id_new_password1">New Password:</label>
                            <input id="id_new_password1" name="new_password1" type="password" class="form-control">
                            {% if form.errors.new_password1 %}
                                <p class="error">{{ form.errors.new_password1 }}</p>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="id_new_password2">Confirm New Password:</label>
                            <input id="id_new_password2" name="new_password2" type="password" class="form-control">
                            {% if form.errors.new_password2 %}
                                <p class="error">{{ form.errors.new_password2 }}</p>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-10 col-sm-offset-1">
                        <input type='submit' class='btn btn-finish btn-primary pull-right' name='update' value='Update' />
                    </div>
                </div>
                </form>

            </div>
        </div><!-- end row -->
    </div>
</div>

{% endblock %}

templates/map.html
{% load static %}
<html>
  <head>
    <title>Map</title>
<!--    <script type="module" src="{% static 'js/index.js' %}"></script>-->
<!--    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>-->

<!--    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />-->
<!--    <link rel="stylesheet" href="{% static 'css/new_carousel.css' %}">-->
  </head>
  <body>
    <!--The div element for the map -->
    <br/>
    <h2 class="map-title">Find houses and flats on the map</h2>
    <div id="map"></div>

    <!-- prettier-ignore -->

<!--    <script src="https://unpkg.com/@googlemaps/markerclusterer/dist/index.min.js"></script>-->
<!--    <script>(g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.listing||(b.listing={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".listing."+q);a.src=`https://maps.${c}apis.com/listing/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})-->
<!--        ({key: "AIzaSyD0-JXyLIKfRXOy5kKKDmpQNW33iA9qSlc", v: "weekly"});</script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/anythingslider@3.18.2/dist/anythingslider.min.js"></script>
  </body>
</html>

templates/register-login.html
{% extends 'base.html' %}
{%  load static %}


{% block title %} Register {% endblock %}

{% block content %}
<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Home New account / Sign in </h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->

<div class="page-content">
    <!-- register-area -->
    <div class="register-area" style="background-color: rgb(249, 249, 249);">
        <div class="container">
            <div class="col-md-6">
                <div class="box-for overflow">
                    <div class="col-md-12 col-xs-12 register-blocks">
                        <h2>New account : </h2>
                        <form action="{% url 'users:register' %}" method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                                {% for field in register_form %}
                                    <div class="form-group">
                                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {% if field.field.widget.input_type != "password" %}
                                            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}">
                                        {% else %}
                                            <input type="password" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}">
                                        {% endif %}
                                    </div>
                                {% endfor %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-default">Register</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="box-for overflow">
                    <div class="col-md-12 col-xs-12 login-blocks">
                        <h2>Login : </h2>
                        <form action="{% url 'users:login' %}" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" class="form-control" id="username" name="username">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-default">Log in</button>
                            </div>
                        </form>

                        <br>
                        <h2>Social login :  </h2>
                        <p>
                            <a class="login-social" href="#"><i class="fa fa-google-plus"></i>&nbsp;Gmail</a>
                            <a class="login-social" href="#"><i class="fa fa-facebook"></i>&nbsp;Facebook</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/submit-property.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Submit Property{% endblock %}
{% block link %}
<script type="module" src="{% static 'js/submit_index.js' %}"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
{% endblock %}
{% block content %}
<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Submit new property</h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->

<!-- property area -->
<div class="content-area submit-property" style="background-color: #FCFCFC;">&nbsp;
    <div class="container">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in listing_form %}
                {% if field.name == 'lat' %}
                <div id="map" style="width: 400px; height: 300px;"></div>
                {% endif %}
                {% if field.name == 'lat' or field.name == 'long' %}
                    <div>
                    {{ field.errors }}
                    {{ field }}
                    </div>
                {% else %}
                <div>
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                </div>
                {% endif %}
            {% endfor %}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</div>


<script>(g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})
    ({key: "AIzaSyD0-JXyLIKfRXOy5kKKDmpQNW33iA9qSlc", v: "weekly"});</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_region').change(function() {
            var regionId = $(this).val();
            if(regionId) {
                $.ajax({
                    url: 'get_cities/',
                    type: 'GET',
                    data: {'region_id': regionId},
                    success: function(data) {
                        $('#id_city').empty().append($('<option>').text('Select City').attr('value', ''));
                        $.each(data, function(key, value) {
                            var option = $('<option>').text(value.name).attr('value', value.id);
                            option.data('lat', value.lat);
                            option.data('long', value.long);
                            $('#id_city').append(option);
                        });
                    }
                });
            } else {
                $('#id_city').empty();
            }
        });
    });
</script>

{% endblock %}

templates/update-user.html
{% extends 'base.html' %}
{%  load static %}

{% block title %} Update account {% endblock %}

{% block content %}

<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Update account:</h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->

<div class="page-content">
    <!-- register-area -->
    <div class="register-area" style="background-color: rgb(249, 249, 249);">
        <div class="container">
            <div class="col-md-6">
                <div class="box-for overflow">
                    <div class="col-md-12 col-xs-12 register-blocks">
                        <h2>Update account : </h2>
                        <form action="{% url 'users:update_user' %}" method="POST">
                            {% csrf_token %}
                            {% for field in update_form %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                                    {% if field.name == "is_agent" %}
                                        <input name="is_agent" type="checkbox" class="form-control" id="is_agent" {% if field.value %} checked {% endif %}>
                                    {% else %}
                                        <input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" value="{{ field.value }}">
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <div class="text-center">
                                <button type="submit" class="btn btn-default">Update account</button>
                                <a href="{% url 'users:change_password' %}" class="btn btn-default">Change Password</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/update_profile.html
{%  extends 'base.html' %}
{%  load static %}

{% block title %} Profile update {% endblock %}

{% block content %}


<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Hello : <span class="orange strong">{{ username }}</span></h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->

<div class="content-area user-profiel" style="background-color: #FCFCFC;">&nbsp;
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 profiel-container">

                <form action="{% url 'users:update_profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="profiel-header">
                        <h3>
                            <b>UPDATE</b> YOUR PROFILE <br>
                            <small>Modify your information here.</small>
                        </h3>
                        <hr>
                    </div>
                    <div class="clear">
                        <div class="col-sm-3 col-sm-offset-1">
                            <div class="picture-container">
                                <div class="picture">
                                    <img src="{{ profile_form.instance.profile_image.url }}" class="picture-src" id="wizardPicturePreview" title="">
                                    <input type="file" id="wizard-picture" name="profile_image">
                                </div>
                                <h6>Change Picture</h6>
                            </div>
                        </div>

                        <div class="col-sm-3 padding-top-25">
                            <div class="form-group">
                                <label>First Name </label>
                                <input name="first_name" type="text" class="form-control" value="{{ profile_form.instance.first_name }}">
                            </div>
                            <div class="form-group">
                                <label>Last Name </label>
                                <input name="last_name" type="text" class="form-control" value="{{ profile_form.instance.last_name }}">
                            </div>
                        </div>
                    </div>

                    <div class="clear">
                        <br>
                        <hr>
                        <br>
                        <div class="col-sm-5 col-sm-offset-1">
                            <div class="form-group">
                                <label>Telegram Username </label>
                                <input name="telegram_username" type="text" class="form-control" value="{{ profile_form.instance.telegram_username }}">
                            </div>
                            <div class="form-group">
                                <label>Website :</label>
                                <input name="website" type="text" class="form-control" value="{{ profile_form.instance.website }}">
                            </div>
                        </div>

                        <div class="col-sm-5">
                            <div class="form-group">
                                <label>Email </label>
                                <input name="email" type="email" class="form-control" value="{{ profile_form.instance.email }}">
                            </div>
                            <div class="form-group">
                                <label>Phone Number </label>
                                <input name="phone_number" type="text" class="form-control" value="{{ profile_form.instance.phone_number }}">
                            </div>
                            <div class="form-group">
                                <label>Is Agent </label>
                                <input name="is_agent" type="checkbox" class="form-control" {% if profile_form.instance.is_agent %} checked {% endif %}>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-5 col-sm-offset-1">
                        <br>
                        <input type='submit' class='btn btn-finish btn-primary' name='finish' value='Update' />
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/user-properties.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        <div class="page-head"> 
            <div class="container">
                <div class="row">
                    <div class="page-head-content">
                        <h1 class="page-title">List Layout With Sidebar</h1>               
                    </div>
                </div>
            </div>
        </div>
        <!-- End page header -->

        <!-- property area -->
        <div class="content-area recent-property" style="background-color: #FFF;">
            <div class="container">   
                <div class="row">

                    <div class="col-md-9 pr-30 padding-top-40 properties-page user-properties">

                        <div class="section"> 
                            <div class="page-subheader sorting pl0 pr-10">


                                <ul class="sort-by-list pull-left">
                                    <li class="active">
                                        <a href="javascript:void(0);" class="order_by_date" data-orderby="property_date" data-order="ASC">
                                            Property Date <i class="fa fa-sort-amount-asc"></i>					
                                        </a>
                                    </li>
                                    <li class="">
                                        <a href="javascript:void(0);" class="order_by_price" data-orderby="property_price" data-order="DESC">
                                            Property Price <i class="fa fa-sort-numeric-desc"></i>						
                                        </a>
                                    </li>
                                </ul><!--/ .sort-by-list-->

                                <div class="items-per-page pull-right">
                                    <label for="items_per_page"><b>Property per page :</b></label>
                                    <div class="sel">
                                        <select id="items_per_page" name="per_page">
                                            <option value="3">3</option>
                                            <option value="6">6</option>
                                            <option value="9">9</option>
                                            <option selected="selected" value="12">12</option>
                                            <option value="15">15</option>
                                            <option value="30">30</option>
                                            <option value="45">45</option>
                                            <option value="60">60</option>
                                        </select>
                                    </div><!--/ .sel-->
                                </div><!--/ .items-per-page-->
                            </div>

                        </div>

                        <div class="section"> 
                            <div id="list-type" class="proerty-th-list">
                                <div class="col-md-4 p0">
                                    <div class="box-two proerty-item">
                                        <div class="item-thumb">
                                            <a href="property-1.html" ><img src="{% static 'assets/img/demo/property-3.jpg' %}"></a>
                                        </div>
                                        <div class="item-entry overflow">
                                            <h5><a href="property-1.html"> Super nice villa </a></h5>
                                            <div class="dot-hr"></div>
                                            <span class="pull-left"><b> Area :</b> 120m </span>
                                            <span class="proerty-price pull-right"> $ 300,000</span>
                                            <p style="display: none;">Suspendisse ultricies Suspendisse ultricies Nulla quis dapibus nisl. Suspendisse ultricies commodo arcu nec pretium ...</p>
                                            <div class="property-icon">
                                                <img src="{% static 'assets/img/icon/bed.png' %}">(5)|
                                                <img src="{% static 'assets/img/icon/shawer.png' %}">(2)|
                                                <img src="{% static 'assets/img/icon/cars.png' %}">(1)  

                                                <div class="dealer-action pull-right">                                        
                                                    <a href="submit-property.html" class="button">Edit </a>
                                                    <a href="#" class="button delete_user_car">Delete</a>
                                                    <a href="property-1.html" class="button">View</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>                             
                            </div>
                        </div>
                        <div class="section"> 
                            <div class="pull-right">
                                <div class="pagination">
                                    <ul>
                                        <li><a href="#">Prev</a></li>
                                        <li><a href="#">1</a></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#">Next</a></li>
                                    </ul>
                                </div>
                            </div>                
                        </div>

                    </div>       

                    <div class="col-md-3 p0 padding-top-40">
                        <div class="blog-asside-right">
                            <div class="panel panel-default sidebar-menu wow fadeInRight animated" >
                                <div class="panel-heading">
                                    <h3 class="panel-title">Hello Kimaro</h3>
                                </div>
                                <div class="panel-body search-widget">

                                </div>
                            </div>

                            <div class="panel panel-default sidebar-menu wow fadeInRight animated">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Recommended</h3>
                                </div>
                                <div class="panel-body recent-property-widget">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}